"use strict";class Player{constructor(t,e){this.name=t,this.type=e,this.hand=[],this.totalValue=0,this.soft=!1,this.isAlive=!0,this.sound=new Sound,this.randomHit=Math.floor(Math.random()*this.sound.soundsHit.length)+0,this.result="",this.bet=0,this.lastBet=0,this.betSaved=[],this.doubled=!1}reset(){this.hand=[],this.cardCovered=[],this.totalValue=0,this.soft=!1,this.isAlive=!0,this.result="",this.doubled=!1}getCard(){if(!this.isAlive)return;let t=deck.deck.shift();return this.hand.push(t),Object.entries(t)[3][1]}checkHand(t){if(!this.isAlive)return;for(let e of(this.totalValue=0,this.hand))console.log(this.name,e);for(let s of this.hand)this.totalValue+=Object.entries(s)[2][1];let i=this.hand.filter(t=>"Ace"===t.title);if(console.log(this.name,"Aces: "+i.length),i.length>0){if(this.totalValue<21)this.soft=!0,console.log("Aces: "+i.length+" | Soft: "+this.soft);else if(this.totalValue>21){let l=i.length;do this.totalValue-=10,l--;while(this.totalValue>21&&l>0);0==l?this.soft=!1:this.soft=!0,console.log("Aces: "+i.length+" | Soft: "+this.soft)}}return(console.log(this.name,"totalValue: "+this.totalValue),document.getElementById("result"+this.name).innerHTML=this.totalValue,21==this.totalValue&&2==this.hand.length)?(console.log(this.name+": Black Jack"),this.renderResult("Black Jack"),this.isAlive=!1,this.result="won","Black Jack!"):21==this.totalValue&&this.hand.length>2?(console.log(this.name+": 21"),"dealer"!=this.type&&this.renderResult("21"),this.isAlive=!1,"21"):this.totalValue>21?(console.log(this.name+": Bust"),this.renderResult("Bust"),"ai"==this.type&&("normal"==t?this.sound.swear():"strong"==t&&this.sound.swearStrong()),this.isAlive=!1,this.result="lost","Bust"):("Dealer"!=this.name&&console.log(this.name+": Card?"),"Card?")}renderResult(t){let e=document.getElementById("renderResult"+this.name);e.innerHTML=t,e.classList.contains("fieldPlayers__container__fieldCards__renderResult--active")||e.classList.toggle("fieldPlayers__container__fieldCards__renderResult--active")}setResult(t){this.result=t}renderCard(t,e){let s=document.createElement("img");s.src="assets/images/cards/"+t+".png",s.className="fieldPlayers__container__fieldCards__imgCard         roll-in-blurred-top","dealer"==this.type&&2==this.hand.length&&(s.className+=" flip-scale-up-hor");let i=document.getElementById("renderResult"+this.name);document.getElementById("cards"+this.name).insertBefore(s,i),document.getElementById("cards"+e).className="d-flex flex-nowrap          fieldPlayers__container__fieldCards",this.sound.draw()}createPlayer(t){let e=document.createElement("div");if(e.id="container"+this.name,e.className="fieldPlayers__container",e.innerHTML+="<div id="+this.name+' class="d-flex align-items-bottom      fieldPlayers__container__totalValue"><p id=result'+this.name+` class="m-0                fieldPlayers__container__totalValue__text"></p>
                            </div>
                            <div id=cards`+this.name+`>
                                <p id=renderResult`+this.name+` class="fieldPlayers__container__fieldCards__renderResult"></p>
                            </div>`,"dealer"!=this.type&&(e.innerHTML+="<div id=buttons"+this.name+` class="d-flex   fieldPlayers__container__buttons">
                                    <button id=buttonHit`+this.name+' class="btn fieldPlayers__container__buttons__Hit" onclick=buttonHit(\''+this.name+`')>
                                        <i class="fas fa-plus"></i>
                                    </button>
                                    <button id=buttonStand`+this.name+' class="btn fieldPlayers__container__buttons__Stand" onclick=buttonStand(\''+this.name+`')>
                                        <i class="fas fa-ban"></i>
                                    </button>
                                    <button id=buttonDouble`+this.name+' class="btn fieldPlayers__container__buttons__Double" onclick=buttonDouble(\''+this.name+`')> x2 </button>
                                    <button id=buttonSplit`+this.name+' class=" btn fieldPlayers__container__buttons__Split" onclick=buttonSplit(\''+this.name+`')>
                                        <i class="fas fa-arrows-alt-h"></i>
                                    </button>
                                </div>`),"dealer"==this.type)document.getElementById("fieldDealer").appendChild(e);else{document.getElementById("fieldPlayer"+t).appendChild(e);let s=document.getElementById("bet"+this.name);null==s&&((s=document.getElementById("betPlayer"+t)).id="bet"+this.name)}}addButtons(){if("player"==this.type){document.getElementById("buttonHit"+this.name).classList.toggle("fieldPlayers__container__buttons__Hit--active");document.getElementById("buttonStand"+this.name).classList.toggle("fieldPlayers__container__buttons__Stand--active");document.getElementById("buttonDouble"+this.name).classList.toggle("fieldPlayers__container__buttons__Double--active");let t;Object.entries(this.hand[0])[2][1]==Object.entries(this.hand[1])[2][1]&&document.getElementById("buttonSplit"+this.name).classList.toggle("fieldPlayers__container__buttons__Split--active")}}removeButtons(t){let e=[];for(let s of e=!0==t?["Double","Split"]:["Hit","Stand","Double","Split"]){let i=document.getElementById("button"+s+this.name);i.classList.contains("fieldPlayers__container__buttons__"+s+"--active")&&i.classList.toggle("fieldPlayers__container__buttons__"+s+"--active")}}soundHit(){this.hit=this.sound.soundsHit[this.randomHit],this.hit.playbackRate=1.5,this.hit.play()}getBet(t){this.bet=0;let e=document.getElementById("bet"+this.name).querySelectorAll(".fieldChips__container__chip__img"),s=[];for(let i=0;i<e.length;i++)e[i].classList.contains("chip1")?s.push(1):e[i].classList.contains("chip5")?s.push(5):e[i].classList.contains("chip10")?s.push(10):e[i].classList.contains("chip50")?s.push(50):e[i].classList.contains("chip100")&&s.push(100);for(let l of s)this.bet+=l;return!0==t&&(this.betSaved=e),console.log(this.name+" bet "+this.bet),this.lastBet=this.bet,this.bet}cashUp(){switch(this.result){case"won":return this.bet;case"lost":return-this.bet;case"standoff":return 0}}}